from fastapi import APIRouter, Response
from pydantic import BaseModel
from typing import List, Dict, Any
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.utils import simpleSplit
import io

router = APIRouter()

class ExportRequest(BaseModel):
    chat_history: List[Dict[str, Any]]
    user_id: int
    role: str

@router.post("/pdf")
async def generate_pdf(request: ExportRequest):
    buffer = io.BytesIO()
    p = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter
    
    # Header
    p.setFont("Helvetica-Bold", 16)
    p.drawString(50, height - 50, "Karnataka State Police - Drishti AI Report")
    
    p.setFont("Helvetica", 10)
    p.drawString(50, height - 70, f"Generated by User ID: {request.user_id} ({request.role})")
    
    y = height - 100
    p.setFont("Helvetica", 12)
    
    for msg in request.chat_history:
        role = "Officer" if msg.get("role") == "user" else "Drishti AI"
        text = f"{role}: {msg.get('content')}"
        
        lines = simpleSplit(text, "Helvetica", 12, width - 100)
        for line in lines:
            if y < 50:
                p.showPage()
                y = height - 50
                p.setFont("Helvetica", 12)
            p.drawString(50, y, line)
            y -= 20
            
        y -= 10 # Extra space between messages
        
    p.save()
    buffer.seek(0)
    
    headers = {
        'Content-Disposition': 'attachment; filename="drishti_report.pdf"'
    }
    
    return Response(content=buffer.getvalue(), headers=headers, media_type="application/pdf")
